import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";


 
import { cn } from "@/lib/utils"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
 

export const metadata: Metadata = {
  title: "SevenLove",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.jpg",
  },
  openGraph: {
    title: "SevenLove",
    description: "Blog chia sẻ ",
    url: "https://my-blog-gx7c.vercel.app/",
    siteName: "SevenLove",
    images: [
      {
        url: "https://i.pinimg.com/736x/f0/19/56/f01956faa4135f0b30cb9a90f31bb662.jpg", // Path to your Open Graph image
        width: 1200,
        height: 630,
        alt: "SevenLove Open Graph Image",
      },
    ],
    locale: "en_US",
    type: "website", // You can change this to 'article' or other types if needed
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>{children}</body>
    </html>
  );
}
